# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eryndor RP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/sunl1nx/EryndorLauncher"
mediaTwitterURL = "https://x.com/sunl1nx"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Sunl1nx"
mediaDiscordURL = "https://discord.gg/56XCPQQpbW"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/Sunl1nx/EL/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ERYNDOR RP"
welcomeDescription = "Perdu au cœur d'un labyrinthe, vous y avez été envoyé après vous être réveillé dans une cuve dans un laboratoire... Qui étiez vous avant ? Peut-être que vous l'apprendrez au cours de votre aventure."
welcomeDescCTA = "Vous etes a deux pas des terres d'Eryndor RP"
